"""Add missing roles to user_roles enum

Revision ID: b6496808b39e
Revises: 2a138344eb0c
Create Date: 2025-12-18 12:38:54.290467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6496808b39e'
down_revision = '2a138344eb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('judge', 'clerk', 'admin', 'registrar', 'magistrate', 'administrator', name='user_roles'),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.Enum('judge', 'clerk', 'admin', 'registrar', 'magistrate', 'administrator', name='user_roles'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
